### ISSUE TITLE
extend event table to use full screen height

### ISSUE THREAD

**Issue by dheidemann** [FachschaftMathPhysInfo/pepp#18]
**not important, just because it bothers me**
I think it is better practice for the form in desktop version to extend to the full screen height and collapse (scrollable) when needed instead of using a fixed table height. current state is that it can happen that people with smaller screens (smaller than Macbook 13.3`) need to scroll the whole form which we wanted to dodge initially

**Comment by Plebysnacc** [comment]
Didn't notice it as I was only testing on small 13" Mac. 

Might wanna start testing on bigger Screens before doing PRs

**Comment by Plebysnacc** [comment]
Heyo @dheidemann, I'm unsure what the desired outcome is, can you provide an image of the issue and a proposed change?
