### ISSUE TITLE
fix nextjs build

### ISSUE THREAD

**Issue by dheidemann** [FachschaftMathPhysInfo/pepp#43]

**Comment by Plebysnacc** [comment]
Any idea what the issue is? Build ran thru in the pr

**Comment by dheidemann** [comment]
yes, also checked it locally where the build was successfully. Now the pipeline fails, as well as local build via docker

**Comment by Plebysnacc** [comment]
I'll assign the ticket to you then, hf

**Comment by dheidemann** [comment]
i am at least as confused as you ma man
