### ISSUE TITLE
Trim Seconds in Event-Table

### ISSUE THREAD

**Issue by Plebysnacc** [FachschaftMathPhysInfo/pepp#46]
Currently the table shows HH/mm/ss in the "to" and "from" fields. We should probably trim that to HH/mm.

Proposed Solutions
- trim the complete date
- trim the visualization of the date in the table

**Comment by Plebysnacc** [comment]
@dheidemann, is trimming the seconds a problem for the API?

**Comment by dheidemann** [comment]
> @dheidemann, is trimming the seconds a problem for the API?

no.
